"""
Django settings for InDJ_MIR project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoModelPermissions',
    )
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'indj_mir',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'indj_mir.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'indj_mir.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'indj',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

INPUT_PATH_MP3 = '/home/dinhkhoi1/data/songs/'
OUTPUT_PATH_WAV = '/home/dinhkhoi1/data/songs'
BUCKET_NAME = 'indj-audiosource'
PREFIX_YOUTUBE = 'youtube'
PREFIX = 'mp3s'
OUTPUT_PATH_HDF5 = '/home/dinhkhoi1/data/songs/'
BUCKET_HDF5 = 'indj-features-extraction'
BUCKET_TRAINING_DATA = 'indj-training-data'
EXCEL_FILE_DATA_TRAINING = '/home/dinhkhoi1/data/pdalbumlist-playlist.xls'
EXCEL_SONGS_DATA = '/home/dinhkhoi1/data/songs.xlsx'
CHANNELS_HOME = '/home/dinhkhoi1/data/channels/channels_home.h5'
TOP_CHANNELS_HOME = '/home/dinhkhoi1/data/channels/top_channels_home.h5'
CHANNELS_CAST = '/home/dinhkhoi1/data/channels/channels_cast.h5'
TOP_CHANNELS_CAST = '/home/dinhkhoi1/data/channels/top_channels_cast.h5'
CHANNELS_RADIO = '/home/dinhkhoi1/data/channels/channels_radio.h5'
TOP_CHANNELS_RADIO = '/home/dinhkhoi1/data/channels/top_channels_radio.h5'
INPUT_PATH_GEOLOCATION = '/home/dinhkhoi1/data/geolocation/'
PATH_CHANNEL_IMAGE = '/home/dinhkhoi1/data/channel_image'